imports:
    - { resource: config_dev.yml }

parameters:
    template_directory: "%kernel.root_dir%/../tests/fixtures/templates"
    default_sender_email: "test@example.com"
    default_sender_name: "Test Default Sender"
    mailer_record_messages: true
    mailer_deliver_messages: false
    env(ENVELOPER_SMTP_HOST): mailhog
    env(ENVELOPER_SMTP_USER): ~
    env(ENVELOPER_SMTP_PASSWORD): ~
    env(ENVELOPER_SMTP_PORT): 1025
    env(ENVELOPER_DB_DSN): "sqlite:///enveloper_test.sqlite"

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false
